server:
  port: 8080
logging:
  level:
    web: info
spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:postgresql://warehouse-db-postgres:5432/postgres
    username: postgres
    password: pass
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        default-page-size: 10
        max-page-size: 500
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
